### ISSUE TITLE
Nil library referenced but not available

### ISSUE THREAD

**Issue by Salgat** [encratite/heroin_glands#1]
My best guess is this is a private general purpose library. Unfortunately cannot find any trace of it online, which breaks the only external dependency for building this project.

**Comment by encratite** [comment]
I'm not entirely sure what you're trying to do but I suspect it's a hopeless undertaking. This project is terribly outdated and I doubt that it would work with the latest version of the client. In fact I'm surprised that you're trying at all. What's your goal here?

Anyway, I dug up the missing library and uploaded it for you. It's from 2008. Mental.
https://github.com/encratite/nil

**Comment by Salgat** [comment]
Pretty sure you're a blizzhacker from the old days, several sources reference both your code and RedVex for parsing Diablo 2 packets. Thank you for uploading that library!

https://web.archive.org/web/20140706010534/http://www.blizzhackers.cc/viewtopic.php?t=406445

**Comment by encratite** [comment]
Yeah, that's right. I used to hang out with Cthulhon, lord2800, Gary13579, darawk etc. on IRC (#bhdev). I'm afraid I haven't talked to any of them in ages, though. I wonder what they're up to now.
